arttime/arttime-webapp/src/main/java/com/artezio/arttime/web/ProjectBean.java
package com.artezio.arttime.web;

import java.io.Serializable;
import java.util.Date;
import java.util.Map;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.ExternalContext;
import javax.inject.Inject;

import com.artezio.arttime.datamodel.Participation;
import com.artezio.arttime.datamodel.Project;
import com.artezio.arttime.services.repositories.ProjectRepository;

@ManagedBean
@ViewScoped
public class ProjectBean implements Serializable {
    private static final long serialVersionUID = -5685248912502538750L;

    private Date startFrom;
    private String selectedTab;
    private Project project;
    @Inject
    private ExternalContext externalContext;
    private Participation participation;
    @Inject
    private ProjectRepository projectRepository;

    @PostConstruct
    public void init() {
	Map<String, String> requestParams = externalContext.getRequestParameterMap();
	String projectCode = requestParams.get("project");
	this.selectedTab = requestParams.get("selectedTab");
	this.project = (projectCode == null) ? new Project() : projectRepository.findProject(projectCode);
	participation = new Participation(project.getDefaultWorkdaysCalendar());
    }

    public void addNew() {
	project = new Project();
    }

    public Project getProject() {
	return project;
    }

    public void setProject(Project project) {
	this.project = project;
    }

    public Date getStartFrom() {
	return startFrom;
    }

    public void setStartFrom(Date startFrom) {
	this.startFrom = startFrom;
    }

    public String getSelectedTab() {
	return selectedTab;
    }

    public void setSelectedTab(String selectedTab) {
	this.selectedTab = selectedTab;
    }

    public void update(Project project) {
	projectRepository.update(project);
    }

    public void create(Project project) {
	projectRepository.create(project);
    }

    public void remove(Project project) {
	projectRepository.remove(project);
    }

    public void delete(Participation participation) {
	project.getTeam().remove(participation);
    }

    public Participation getParticipation() {
	return participation;
    }

    public void setParticipation(Participation participation) {
	this.participation = participation;
    }

    public void addNewParticipation() {
	project.addParticipation(participation);
	participation = new Participation(project.getDefaultWorkdaysCalendar());
    }
}

arttime/arttime-webapp/src/main/java/com/artezio/arttime/web/ProjectStatusBean.java
package com.artezio.arttime.web;

import java.io.Serializable;
import java.util.Map;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.ExternalContext;
import javax.inject.Inject;
import javax.validation.constraints.AssertTrue;

import com.artezio.arttime.datamodel.Project;
import com.artezio.arttime.datamodel.ProjectStatus;
import com.artezio.arttime.datamodel.ProjectStatus.Status;
import com.artezio.arttime.services.repositories.ProjectRepository;

@ManagedBean
@ViewScoped
public class ProjectStatusBean implements Serializable {
	private static final long serialVersionUID = -2232557902247779429L;
	private Project project;
	@Inject
	private ExternalContext externalContext;
	private ProjectStatus projectStatus = new ProjectStatus();
	@Inject
	private ProjectRepository projectRepository;

	@PostConstruct
	public void init() {
		Map<String, String> requestParams = externalContext.getRequestParameterMap();
		String projectCode = requestParams.get("project");
		this.project = projectRepository.findProject(projectCode);
	}

	public Project getProject() {
		return project;
	}

	public ProjectStatus getProjectStatus() {
		return projectStatus;
	}

	public void setProjectStatus(ProjectStatus projectStatus) {
		this.projectStatus = projectStatus;
	}

	public void addStatus() {
		project.addStatus(projectStatus);
		projectStatus = new ProjectStatus();
	}

	public Status[] getStatuses() {
		return Status.values();
	}

	public void delete(ProjectStatus projectStatus) {
		project.getStatuses().remove(projectStatus);
	}

}

arttime/arttime-webapp/src/main/java/com/artezio/arttime/web/ProjectsBean.java
package com.artezio.arttime.web;

import java.io.Serializable;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import org.richfaces.component.SortOrder;

@ManagedBean
@ViewScoped
public class ProjectsBean implements Serializable {
	private static final long serialVersionUID = 6385561178974142829L;
			
	private SortOrder managerOrder = SortOrder.unsorted;
	private SortOrder projectCodeOrder = SortOrder.ascending;		
	
	public SortOrder getProjectCodeOrder() {
		return projectCodeOrder;
	}
	
	public void setProjectCodeOrder(SortOrder projectCodeOrder) {
		this.projectCodeOrder = projectCodeOrder;
	}
	
	public SortOrder getManagerOrder() {
		return managerOrder;
	}
	
	public void setManagerOrder(SortOrder managerOrder) {
		this.managerOrder = managerOrder;
	}
	
	public void sortByCode() {
        managerOrder = SortOrder.unsorted;        
        if (projectCodeOrder.equals(SortOrder.ascending)) {
        	setProjectCodeOrder(SortOrder.descending);
        } else {
        	setProjectCodeOrder(SortOrder.ascending);
        }
    }
	
	public void sortByManager() {
		projectCodeOrder = SortOrder.unsorted;        
        if (managerOrder.equals(SortOrder.ascending)) {
        	setManagerOrder(SortOrder.descending);
        } else {
        	setManagerOrder(SortOrder.ascending);
        }
    }					
}

arttime/arttime-webapp/src/main/webapp/pages/project/toolbar/createProject.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml" 
	xmlns:h="http://java.sun.com/jsf/html" xmlns:ui="http://java.sun.com/jsf/facelets"	
	xmlns:c="http://java.sun.com/jstl/core" xmlns:f="http://java.sun.com/jsf/core" 
	xmlns:p="http://primefaces.org/ui" xmlns:rich="http://richfaces.org/rich">
	
	<rich:toolbar styleClass="toolBar">
		<rich:toolbarGroup location="right">
			<c:set var="project" value="#{projectBean.project}"/>
			<p:commandButton value="#{messages['button.create']}" 
	    			action="create" actionListener="#{projectBean.create(project)}" 
	    			styleClass="avoidChangeTracking avoidChangesConfirmation"
	    			ajax="false"/>
	    	<p:commandButton value="#{messages['button.cancel']}" 
	    			action="cancel" 
	    			immediate="true" 
	    			styleClass="avoidChangeTracking avoidChangesConfirmation"
	    			ajax="false"/>	
		</rich:toolbarGroup>
	</rich:toolbar>							
</ui:composition>	

arttime/arttime-webapp/src/main/webapp/pages/project/toolbar/editProject.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml" 
	xmlns:h="http://java.sun.com/jsf/html" xmlns:ui="http://java.sun.com/jsf/facelets"	
	xmlns:c="http://java.sun.com/jstl/core" xmlns:f="http://java.sun.com/jsf/core" 
	xmlns:p="http://primefaces.org/ui" xmlns:rich="http://richfaces.org/rich">
	
	<rich:toolbar styleClass="toolBar">
		<rich:toolbarGroup location="left" rendered="#{topBar}">
			<c:set var="project" value="#{projectBean.project}"/>
			<p:button value="#{messages['project.button.team']}" 
					outcome="switchTab" includeViewParams="true"
					styleClass="avoidChangeTracking leftPositionButton #{projectBean.selectedTab == 'team' ? 'selected' : ''}">
				<f:param name="project" value="#{project.code}"/>
				<f:param name="selectedTab" value="team"/>
			</p:button>	
			<p:button value="#{messages['project.button.details']}" 
					outcome="switchTab" includeViewParams="true"
					styleClass="avoidChangeTracking middlePositionButton #{projectBean.selectedTab == 'details' ? 'selected' : ''}">
				<f:param name="project" value="#{project.code}"/>
				<f:param name="selectedTab" value="details"/>
			</p:button>				
            <p:button value="#{messages['project.button.statuses']}"
                      outcome="switchTab" includeViewParams="true"
                      styleClass="avoidChangeTracking middlePositionButton #{projectBean.selectedTab == 'statuses' ? 'selected' : ''}">
                <f:param name="project" value="#{project.code}"/>
                <f:param name="selectedTab" value="statuses"/>
            </p:button>
            <p:button value="#{messages['project.button.importSettings']}" 
					outcome="switchTab" includeViewParams="true"
					styleClass="avoidChangeTracking rightPositionButton #{projectBean.selectedTab == 'importSettings' ? 'selected' : ''}">
				<f:param name="project" value="#{project.code}"/>
				<f:param name="selectedTab" value="importSettings"/>
			</p:button>
		</rich:toolbarGroup>
		<rich:toolbarGroup location="right">
			<p:commandButton value="#{messages['button.save']}" 
	    			action="update" actionListener="#{projectBean.update(project)}"
	    			styleClass="avoidChangeTracking avoidChangesConfirmation"
	    			ajax="false"
	    			icon="saveIcon"/>
	    	<p:commandButton value="#{messages['button.cancel']}" 
	    			action="cancel" immediate="true"
	    			styleClass="avoidChangeTracking avoidChangesConfirmation"
	    			ajax="false">    		
	    	</p:commandButton>		
		</rich:toolbarGroup>
	</rich:toolbar>									
</ui:composition>	

arttime/arttime-webapp/src/main/webapp/pages/project/toolbar/projects.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml" 
	xmlns:h="http://java.sun.com/jsf/html" xmlns:ui="http://java.sun.com/jsf/facelets"	
	xmlns:c="http://java.sun.com/jstl/core" xmlns:f="http://java.sun.com/jsf/core" 
	xmlns:p="http://primefaces.org/ui" xmlns:rich="http://richfaces.org/rich">
	
	<c:set var="criteria" value="#{projectsSelectionCriteriaBean.criteria}"/>
	
	<rich:toolbar styleClass="toolBar">		
		<rich:toolbarGroup location="left" itemClass="" >							
			<p:inputText value="#{criteria.searchQuery}"
					placeholder="#{messages['input.placeholder.search']}"
					styleClass="avoidChangeTracking searchInput" 
					rendered="#{topBar}"/>
			<p:commandButton action="search" 
					value=""				 
					styleClass="avoidChangeTracking avoidChangesConfirmation searchButton"
					rendered="#{topBar}"
					ajax="false"/>			
		</rich:toolbarGroup>
		
		<rich:toolbarGroup location="right">
			<p:commandButton value="#{messages['com.artezio.arttime.status.any']}"
					action="#{criteria.setStatus('ANY')}"
					styleClass="avoidChangeTracking avoidChangesConfirmation leftPositionButton #{criteria.status=='ANY'?'selected':''}"
					rendered="#{topBar}"
					ajax="false"/>
			<p:commandButton value="#{messages['com.artezio.arttime.status.active']}"
					action="#{criteria.setStatus('ACTIVE')}"
					styleClass="avoidChangeTracking avoidChangesConfirmation middlePositionButton #{criteria.status=='ACTIVE'?'selected':''}"
					rendered="#{topBar}"
					ajax="false"/>
			<p:commandButton value="#{messages['com.artezio.arttime.status.onHold']}"
					action="#{criteria.setStatus('FROZEN')}"
					styleClass="avoidChangeTracking avoidChangesConfirmation middlePositionButton #{criteria.status=='FROZEN'?'selected':''}"
					rendered="#{topBar}"
					ajax="false"/>
			<p:commandButton value="#{messages['com.artezio.arttime.status.closed']}"
					action="#{criteria.setStatus('COMPLETED')}"
					styleClass="avoidChangeTracking avoidChangesConfirmation rightPositionButton #{criteria.status=='COMPLETED'?'selected':''}"
					rendered="#{topBar}"
					ajax="false"/>
			<p:commandButton value="#{messages['projects.button.addNew']}" 
	    			action="addNew" actionListener="#{projectBean.addNew()}" 
	    			styleClass="avoidChangeTracking avoidChangesConfirmation"
	    			ajax="false"
	    			icon="newIcon"/>
		</rich:toolbarGroup>
	</rich:toolbar>				
</ui:composition>	