arttime/arttime-webapp/src/main/java/com/artezio/arttime/web/WorkloadsBean.java
package com.artezio.arttime.web;

import java.io.Serializable;
import java.util.List;
import java.util.Map;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.ExternalContext;
import javax.inject.Inject;

import com.artezio.arttime.datamodel.Employee;
import com.artezio.arttime.services.repositories.EmployeeRepository;
import com.artezio.arttime.web.criteria.EmployeeSearchCriteriaBean;

@ManagedBean
@ViewScoped
public class WorkloadsBean implements Serializable {
    private static final long serialVersionUID = 1050474595811573237L;
    private Employee employee;
    @Inject
    private ExternalContext externalContext;
    @Inject
    private EmployeeSearchCriteriaBean employeeSearchCriteriaBean;
    @Inject
    private EmployeeRepository employeeRepository;

    @PostConstruct
    public void init() {
	Map<String, String> requestParams = externalContext.getRequestParameterMap();
	String username = requestParams.get("employee");
	this.employee = employeeRepository.find(username);
    }

    public void editWorkload(Employee employee) {
	this.employee = employee;
    }

    public void save() {
	employeeRepository.update(employee);
    }

    public Employee getEmployee() {
	return employee;
    }

    public List<Employee> getEmployees() {
	String searchString = employeeSearchCriteriaBean.getSearchQuery();
	return employeeRepository.getEmployees(searchString);
    }
}

arttime/arttime-webapp/src/main/webapp/layout/checkUnsavedModifications.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
		xmlns:ui="http://java.sun.com/jsf/facelets"
		xmlns:f="http://java.sun.com/jsf/core"
		xmlns:h="http://java.sun.com/jsf/html">

	<h:outputScript>

		function setWindowUnloadMessage() {
			window.onbeforeunload = function() {
				return "#{messages['warning.youHaveUnsavedChanges']}";
			};
		}

		function checkUnsavedModifications() {
			$("input:not(.avoidChangeTracking input)").on("change", setWindowUnloadMessage);
			$("textarea:not(.avoidChangeTracking textarea)").on("change", setWindowUnloadMessage);
			$("select:not(.avoidChangeTracking select)").on("change", setWindowUnloadMessage);
			$(".rf-cal-c").on("click", setWindowUnloadMessage);
			$(".ui-handsontable").on("change", setWindowUnloadMessage);
			$("button:not(.avoidChangeTracking button, .ui-autocomplete button)").on("click", setWindowUnloadMessage);
            $(".hasDatepicker:not(.avoidChangeTracking .hasDatepicker)").on("click", setWindowUnloadMessage);
            $(".ui-autocomplete-panel").on("click", ".ui-autocomplete-item", setWindowUnloadMessage);

			$(".avoidChangeTracking").off("click change", setWindowUnloadMessage);

			$(".avoidChangesConfirmation").click(function() {
				window.onbeforeunload = null;
			});
		};

		window.addEventListener("load", checkUnsavedModifications, false);
	</h:outputScript>

</ui:composition>

arttime/arttime-webapp/src/main/webapp/layout/mainMenu.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"	
	xmlns:c="http://java.sun.com/jstl/core"
	xmlns:rich="http://richfaces.org/rich"
	xmlns:p="http://primefaces.org/ui" 
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:fn="http://java.sun.com/jsp/jstl/functions"
	xmlns:arttime="http://java.sun.com/jsf/composite/components">

	<script type="text/javascript">
	//<![CDATA[
		$( document ).ready(function() {																										
			var menuItems = $("td[id^='mainMenuForm:']");
			$.each( menuItems, function( key, value ) {
				if ($(value).find("div.activeMenuItem").length > 0) {
					$(value).addClass("selectedItem");
				} else {
					$(value).removeClass("selectedItem");
				}								
			});
			
		});
	//]]>				
	</script>

	<h:form id="mainMenuForm">						
 		<rich:toolbar id="mainMenu" itemSeparator="line">
 			<rich:toolbarGroup location="left" itemClass="selectedItem" id="mainMenuGroup">
 				<rich:menuItem onclick="return false;"/>
	 			<rich:menuItem label="#{messages['mainMenu.timesheet']}" 
						action="timesheet"
						rendered="#{request.isUserInRole('employee')}"
						styleClass="#{fn:startsWith(view.viewId, '/pages/timesheet') ? 'activeMenuItem' : ''}" />
				<rich:menuItem label="#{messages['mainMenu.manageEfforts']}" 
						action="manageEfforts" 
						rendered="#{request.isUserInRole('exec') or request.isUserInRole('pm')}"
						styleClass="#{fn:startsWith(view.viewId, '/pages/manageEfforts') ? 'activeMenuItem' : ''}" 
						style="color:red"/>
				<rich:menuItem label="#{messages['mainMenu.reports']}" action="reports"
                        styleClass="#{fn:startsWith(view.viewId, '/pages/reports') ? 'activeMenuItem' : ''}"
                        rendered="#{request.isUserInRole('exec') or request.isUserInRole('pm')}"/>
				<rich:dropDownMenu label="#{messages['mainMemu.dictionaries']}"  					
						rendered="#{request.isUserInRole('exec') or request.isUserInRole('pm')}"					
						styleClass="#{(fn:startsWith(view.viewId, '/pages/hourType') 
									or fn:startsWith(view.viewId, '/pages/calendar') 
									or fn:startsWith(view.viewId, '/pages/project')
									or fn:startsWith(view.viewId, '/pages/workload')) ? 'activeMenuItem' : ''}" >					
					<rich:menuItem label="#{messages['mainMenu.projects']}" action="projects"/>
					<rich:menuItem label="#{messages['mainMenu.workloads']}" action="workloads" rendered="#{request.isUserInRole('exec')}"/>
					<rich:menuItem label="#{messages['mainMenu.calendars']}" action="calendars" rendered="#{request.isUserInRole('exec')}"/>
					<rich:menuItem label="#{messages['mainMemu.hourTypes']}" action="hourTypes" rendered="#{request.isUserInRole('exec')}"/>
				</rich:dropDownMenu>
				<rich:menuItem label="#{messages['mainMenu.notifications']}" 
						action="workTimeProblemsNotification" 
						rendered="#{request.isUserInRole('exec')}"
						styleClass="#{fn:startsWith(view.viewId, '/pages/notifications') ? 'activeMenuItem' : ''}" />
				<rich:dropDownMenu label="#{messages['mainMenu.settings']}" 
						rendered="#{request.isUserInRole('admin')}"
						styleClass="#{fn:startsWith(view.viewId, '/pages/settings') ? 'activeMenuItem' : ''}" >
					<rich:menuItem label="#{messages['mainMenu.settings.employees']}" action="employeeService"/>
					<rich:menuItem label="#{messages['mainMenu.settings.team']}" action="teamTracking"/>
					<rich:menuItem label="#{messages['mainMenu.settings.smtp']}" action="smtp"/>
					<rich:menuItem label="#{messages['mainMenu.settings.synchronization']}" action="synchronization"/>
					<rich:menuItem label="#{messages['mainMenu.settings.security']}" action="security"/>
					<rich:menuItem label="#{messages['mainMenu.settings.notification']}" action="notification"/>
				</rich:dropDownMenu>
			</rich:toolbarGroup>
			<rich:toolbarGroup location="right" itemClass="unselectMenu">
				<rich:menuItem onclick="return false;" styleClass="menuSeparatorRight"
							   rendered="#{fn:startsWith(view.viewId, '/pages/timesheet')}"/>
				<arttime:reportedHoursIndicator rendered="#{fn:startsWith(view.viewId, '/pages/timesheet')}"/>
				<rich:menuItem label="#{(loginBean.loggedEmployee == null) ? '' : loginBean.loggedEmployee.userName}"
                        title="#{messages['mainMenu.logout.title']}"
						action="#{loginBean.logout()}"
						icon="/img/signout.png"
						styleClass="signout"/>
			</rich:toolbarGroup>
		</rich:toolbar>		 
	</h:form>
</ui:composition>

arttime/arttime-webapp/src/main/webapp/layout/template.xhtml
<f:view xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:f="http://java.sun.com/jsf/core"
	xmlns:rich="http://richfaces.org/rich" xmlns:a4j="http://richfaces.org/a4j"
	xmlns:h="http://java.sun.com/jsf/html" xmlns:o="http://omnifaces.org/ui" 
	xmlns:p="http://primefaces.org/ui" contentType="text/html">
<html>
	<h:head>
		<title><ui:insert name="titleHead"/> - ART-TIME</title>
		<f:facet name="first">
			<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
		</f:facet>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />		
		<link href="#{facesContext.externalContext.requestContextPath}/stylesheet/styles.css" rel="stylesheet" type="text/css" />
		<meta http-equiv="cache-control" content="no-cache" />
		<meta http-equiv="expires" content="0" />
		<meta http-equiv="pragma" content="no-cache" />
		<link rel="shortcut icon" href="#{request.contextPath}/img/favicon.ico" />
	</h:head>

	<h:body>
		<h:outputScript name="errorStyleForAutoCompleteButtons.js" library="js"/>
		<h:outputScript name="showTitlesInsideSheet.js" library="js"/>	
		
		<f:metadata>
     		<o:enableRestorableView/>
 		</f:metadata>
		<h:outputScript name="calendarLocales.js" library="js"/>

		<ui:include src="checkUnsavedModifications.xhtml"/>
					
		
		<h:panelGrid columns="4" styleClass="navigationPanel">
			<h:panelGroup layout="block" styleClass="logoStatus">			
				<h:graphicImage value="/img/staticLogo.gif"/>				
			</h:panelGroup>								
						
			<ui:include src="mainMenu.xhtml" />			
			
			<h:panelGroup id="progressBar">
				<ui:insert name="progressBar"/>
			</h:panelGroup>								
		</h:panelGrid>		
		
		<h:panelGroup id="titleBody">
			<div class="predefineStates">
				<ui:insert name="predefineState"/>
			</div>
			<div class="titleBody">			
				<ui:insert name="titleBody"/>
			</div>
			<p:ajaxStatus styleClass="ajaxStatus" oncomplete="addErrorStyleForAutoCompleteButtons()">     
			   	<f:facet name="start">
					<h:graphicImage value="/img/clocklogo-gray.gif"/>
					<h:outputText value="#{messages['ajaxStatus.label']}" />						
			   	</f:facet>     
			</p:ajaxStatus>			
		</h:panelGroup>

        <p:growl id="growl" autoUpdate="true" globalOnly="true"/>

		<h:panelGroup id="container">				
			<ui:insert name="content"/>
		</h:panelGroup>
		
		<h:panelGroup id="copyright">
			<h:outputText value="Artezio, LLC" styleClass="copyrightText"/>
		</h:panelGroup>
		
	</h:body>
</html>
</f:view>